//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoPuntosPublicidad.GPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntoGenericoBE", Namespace="http://gpservice.org/")]
    [System.SerializableAttribute()]
    public partial class PuntoGenericoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubtituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracteristicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDemoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudField, value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudField, value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Subtitulo {
            get {
                return this.SubtituloField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtituloField, value) != true)) {
                    this.SubtituloField = value;
                    this.RaisePropertyChanged("Subtitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Icono {
            get {
                return this.IconoField;
            }
            set {
                if ((object.ReferenceEquals(this.IconoField, value) != true)) {
                    this.IconoField = value;
                    this.RaisePropertyChanged("Icono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Caracteristica {
            get {
                return this.CaracteristicaField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristicaField, value) != true)) {
                    this.CaracteristicaField = value;
                    this.RaisePropertyChanged("Caracteristica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TipoDemo {
            get {
                return this.TipoDemoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDemoField, value) != true)) {
                    this.TipoDemoField = value;
                    this.RaisePropertyChanged("TipoDemo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gpservice.org/", ConfigurationName="GPService.GPServicesSoap")]
    public interface GPServicesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoPunto del espacio de nombres http://gpservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gpservice.org/ObtienePuntosGuardadosLL", ReplyAction="*")]
        GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLResponse ObtienePuntosGuardadosLL(GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento titulo del espacio de nombres http://gpservice.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://gpservice.org/InsertaPuntoGenerico", ReplyAction="*")]
        GeoPuntosPublicidad.GPService.InsertaPuntoGenericoResponse InsertaPuntoGenerico(GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtienePuntosGuardadosLLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtienePuntosGuardadosLL", Namespace="http://gpservice.org/", Order=0)]
        public GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequestBody Body;
        
        public ObtienePuntosGuardadosLLRequest() {
        }
        
        public ObtienePuntosGuardadosLLRequest(GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpservice.org/")]
    public partial class ObtienePuntosGuardadosLLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoPunto;
        
        public ObtienePuntosGuardadosLLRequestBody() {
        }
        
        public ObtienePuntosGuardadosLLRequestBody(string tipoPunto) {
            this.tipoPunto = tipoPunto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtienePuntosGuardadosLLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtienePuntosGuardadosLLResponse", Namespace="http://gpservice.org/", Order=0)]
        public GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLResponseBody Body;
        
        public ObtienePuntosGuardadosLLResponse() {
        }
        
        public ObtienePuntosGuardadosLLResponse(GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpservice.org/")]
    public partial class ObtienePuntosGuardadosLLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<GeoPuntosPublicidad.GPService.PuntoGenericoBE> ObtienePuntosGuardadosLLResult;
        
        public ObtienePuntosGuardadosLLResponseBody() {
        }
        
        public ObtienePuntosGuardadosLLResponseBody(System.Collections.Generic.List<GeoPuntosPublicidad.GPService.PuntoGenericoBE> ObtienePuntosGuardadosLLResult) {
            this.ObtienePuntosGuardadosLLResult = ObtienePuntosGuardadosLLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaPuntoGenericoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaPuntoGenerico", Namespace="http://gpservice.org/", Order=0)]
        public GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequestBody Body;
        
        public InsertaPuntoGenericoRequest() {
        }
        
        public InsertaPuntoGenericoRequest(GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpservice.org/")]
    public partial class InsertaPuntoGenericoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subtitulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string caracteristica;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string icono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tipoDemo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Longitud;
        
        public InsertaPuntoGenericoRequestBody() {
        }
        
        public InsertaPuntoGenericoRequestBody(string titulo, string descripcion, string subtitulo, string caracteristica, string icono, string tipoDemo, string Latitud, string Longitud) {
            this.titulo = titulo;
            this.descripcion = descripcion;
            this.subtitulo = subtitulo;
            this.caracteristica = caracteristica;
            this.icono = icono;
            this.tipoDemo = tipoDemo;
            this.Latitud = Latitud;
            this.Longitud = Longitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertaPuntoGenericoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertaPuntoGenericoResponse", Namespace="http://gpservice.org/", Order=0)]
        public GeoPuntosPublicidad.GPService.InsertaPuntoGenericoResponseBody Body;
        
        public InsertaPuntoGenericoResponse() {
        }
        
        public InsertaPuntoGenericoResponse(GeoPuntosPublicidad.GPService.InsertaPuntoGenericoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gpservice.org/")]
    public partial class InsertaPuntoGenericoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertaPuntoGenericoResult;
        
        public InsertaPuntoGenericoResponseBody() {
        }
        
        public InsertaPuntoGenericoResponseBody(bool InsertaPuntoGenericoResult) {
            this.InsertaPuntoGenericoResult = InsertaPuntoGenericoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPServicesSoapChannel : GeoPuntosPublicidad.GPService.GPServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPServicesSoapClient : System.ServiceModel.ClientBase<GeoPuntosPublicidad.GPService.GPServicesSoap>, GeoPuntosPublicidad.GPService.GPServicesSoap {
        
        public GPServicesSoapClient() {
        }
        
        public GPServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLResponse GeoPuntosPublicidad.GPService.GPServicesSoap.ObtienePuntosGuardadosLL(GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequest request) {
            return base.Channel.ObtienePuntosGuardadosLL(request);
        }
        
        public System.Collections.Generic.List<GeoPuntosPublicidad.GPService.PuntoGenericoBE> ObtienePuntosGuardadosLL(string tipoPunto) {
            GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequest inValue = new GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequest();
            inValue.Body = new GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLRequestBody();
            inValue.Body.tipoPunto = tipoPunto;
            GeoPuntosPublicidad.GPService.ObtienePuntosGuardadosLLResponse retVal = ((GeoPuntosPublicidad.GPService.GPServicesSoap)(this)).ObtienePuntosGuardadosLL(inValue);
            return retVal.Body.ObtienePuntosGuardadosLLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GeoPuntosPublicidad.GPService.InsertaPuntoGenericoResponse GeoPuntosPublicidad.GPService.GPServicesSoap.InsertaPuntoGenerico(GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequest request) {
            return base.Channel.InsertaPuntoGenerico(request);
        }
        
        public bool InsertaPuntoGenerico(string titulo, string descripcion, string subtitulo, string caracteristica, string icono, string tipoDemo, string Latitud, string Longitud) {
            GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequest inValue = new GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequest();
            inValue.Body = new GeoPuntosPublicidad.GPService.InsertaPuntoGenericoRequestBody();
            inValue.Body.titulo = titulo;
            inValue.Body.descripcion = descripcion;
            inValue.Body.subtitulo = subtitulo;
            inValue.Body.caracteristica = caracteristica;
            inValue.Body.icono = icono;
            inValue.Body.tipoDemo = tipoDemo;
            inValue.Body.Latitud = Latitud;
            inValue.Body.Longitud = Longitud;
            GeoPuntosPublicidad.GPService.InsertaPuntoGenericoResponse retVal = ((GeoPuntosPublicidad.GPService.GPServicesSoap)(this)).InsertaPuntoGenerico(inValue);
            return retVal.Body.InsertaPuntoGenericoResult;
        }
    }
}
